"use client";

import { useMemo, useState } from "react";

type ModuleItem = { id: string; name: string; note: string; status: "正常" | "注意" | "建置中" };
type ModuleGroup = { key: string; title: string; subtitle: string; color: string; items: ModuleItem[] };

const groups: ModuleGroup[] = [
  { key:"foundation", title:"基礎資料與危害溝通", subtitle:"建立單一可信資料源", color:"blue", items:[
    {id:"F01",name:"化學品基本資料庫",note:"CAS No.、組成、供應商與用途主檔",status:"正常"},{id:"F02",name:"SDS安全資料表管理",note:"版本、語言、效期與缺漏檢核",status:"注意"},{id:"F03",name:"GHS標示與容器標籤",note:"標示要素及現場標籤產製",status:"正常"},{id:"F05",name:"禁限用及高危害物質辨識",note:"管制清單自動比對與提示",status:"正常"},{id:"F20",name:"法規清單與變更通知",note:"適用法規、責任與期限追蹤",status:"建置中"}]},
  { key:"lifecycle", title:"採購、庫存與生命週期", subtitle:"從引進到廢棄全程留痕", color:"red", items:[
    {id:"F04",name:"新化學品採購前審查",note:"需求、危害、法規及替代方案會簽",status:"注意"},{id:"F06",name:"化學品替代評估",note:"危害、效能與風險移轉比較",status:"建置中"},{id:"F07",name:"庫存、儲位及有效期限",note:"即時存量、位置與逾期預警",status:"正常"},{id:"F08",name:"使用量與流向管理",note:"領用、轉移、退料與質量平衡",status:"正常"},{id:"F15",name:"廢棄化學品與廢棄物流向",note:"暫存、清運、聯單及最終處置",status:"正常"}]},
  { key:"risk", title:"作業風險與健康管理", subtitle:"辨識暴露並驗證控制成效", color:"navy", items:[
    {id:"F09",name:"儲存相容性及分區",note:"不相容矩陣、分區與混存警示",status:"注意"},{id:"F10",name:"作業場所及製程關聯",note:"場所、設備、任務與使用物質關聯",status:"正常"},{id:"F11",name:"職業暴露評估管理",note:"SEG、採樣、OEL與分級決策",status:"注意"},{id:"F12",name:"工程控制與PPE管理",note:"局排、密閉、呼吸防護與效能檢查",status:"正常"},{id:"F13",name:"健康風險與特殊健康管理",note:"健康風險、適性配置與追蹤",status:"正常"}]},
  { key:"compliance", title:"法遵、消防與應變", subtitle:"整合法定申報及事故準備", color:"red", items:[
    {id:"F14",name:"環保法規與申報資料",note:"毒化物、空污、水污與申報資料",status:"建置中"},{id:"F16",name:"消防危險物品管理",note:"分類、管制量、場所與申報",status:"正常"},{id:"F17",name:"緊急應變資訊管理",note:"洩漏情境、器材、通報與應變卡",status:"注意"},{id:"F18",name:"教育訓練與人員資格",note:"職務矩陣、證照與到期提醒",status:"正常"},{id:"F19",name:"稽核、缺失及改善追蹤",note:"查核、矯正預防措施與閉環管理",status:"正常"}]},
  { key:"digital", title:"數位治理與永續整合", subtitle:"串接企業系統並支援決策", color:"blue", items:[
    {id:"F21",name:"管理儀表板與風險預警",note:"跨部門KPI、異常與趨勢洞察",status:"正常"},{id:"F22",name:"ESG與永續資訊揭露",note:"GRI 403、減量與替代績效",status:"建置中"},{id:"F23",name:"行動裝置／QR Code／RFID",note:"現場盤點、查詢與異常回報",status:"正常"},{id:"F24",name:"與既有資訊系統串接",note:"ERP、採購、倉儲、MES與人資",status:"建置中"},{id:"F25",name:"權限、電子簽核與操作紀錄",note:"角色權限、簽核軌跡與稽核證據",status:"正常"}]},
];

const iconPath: Record<string,string>={dashboard:"M4 13h6V4H4v9Zm0 7h6v-4H4v4Zm10 0h6v-9h-6v9Zm0-16v4h6V4h-6Z",modules:"M4 4h6v6H4V4Zm10 0h6v6h-6V4ZM4 14h6v6H4v-6Zm10 0h6v6h-6v-6Z",risk:"M12 3 3.8 7v5c0 4.8 3.5 8.5 8.2 9 4.7-.5 8.2-4.2 8.2-9V7L12 3Zm0 5v5m0 3v.1",inventory:"M4 7.5 12 3l8 4.5V17l-8 4-8-4V7.5Zm0 0 8 4.5 8-4.5M12 12v9",reports:"M5 3h11l3 3v15H5V3Zm11 0v4h3M8 12h8M8 16h8M8 8h4",settings:"M12 8.8a3.2 3.2 0 1 0 0 6.4 3.2 3.2 0 0 0 0-6.4Zm8.2 3.2-.1-1.2 2-1.6-2-3.4-2.5 1a8 8 0 0 0-2-1.2L15.2 3h-4l-.4 2.6a8 8 0 0 0-2 1.2l-2.5-1-2 3.4 2 1.6L6.2 12l.1 1.2-2 1.6 2 3.4 2.5-1a8 8 0 0 0 2 1.2l.4 2.6h4l.4-2.6a8 8 0 0 0 2-1.2l2.5 1 2-3.4-2-1.6.1-1.2Z"};
function Icon({name,size=20}:{name:string;size?:number}){return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={iconPath[name]}/></svg>}

function Gauge({value}:{value:number}){return <div className="gauge-wrap" aria-label={`整體風險指數 ${value} 分`}><svg viewBox="0 0 160 92"><path d="M20 78a60 60 0 0 1 120 0" className="gauge-track"/><path d="M20 78a60 60 0 0 1 120 0" className="gauge-value" pathLength="100" style={{strokeDasharray:`${value} 100`}}/><line x1="80" y1="78" x2={80+47*Math.cos(Math.PI-(Math.PI*value)/100)} y2={78-47*Math.sin((Math.PI*value)/100)} className="needle"/><circle cx="80" cy="78" r="6" className="needle-hub"/></svg><div className="gauge-number"><strong>{value}</strong><span>/100</span></div><div className="gauge-labels"><span>低</span><span>中</span><span>高</span></div></div>}
function Heatmap({industry}:{industry:string}){const rubber=[[1,2,3,4,4],[1,2,3,3,4],[1,2,2,3,4],[1,1,2,3,3],[1,1,2,2,3]],plastic=[[1,2,3,3,4],[1,2,2,3,4],[1,2,3,4,5],[1,1,2,3,4],[1,1,2,2,3]],matrix=industry==="橡膠製品業"?rubber:plastic;return <div className="heatmap" aria-label="化學品風險矩陣熱力圖"><div className="heat-y">嚴重度</div><div className="heat-grid">{matrix.flatMap((row,r)=>row.map((v,c)=><button key={`${r}-${c}`} className={`heat heat-${v}`} title={`嚴重度 ${5-r}、可能性 ${c+1}：風險 ${v}`} aria-label={`嚴重度 ${5-r} 可能性 ${c+1} 風險等級 ${v}`}>{r===0&&c===4?"7":r===1&&c===3?"12":r===2&&c===2?"18":""}</button>))}</div><div className="heat-x">發生可能性 →</div></div>}
function Donut({value}:{value:number}){return <div className="donut" style={{"--pct":`${value*3.6}deg`} as React.CSSProperties}><div><strong>{value}%</strong><span>完成率</span></div></div>}

export default function Home(){
 const[industry,setIndustry]=useState("塑膠製品業"),[query,setQuery]=useState(""),[status,setStatus]=useState("全部"),[selected,setSelected]=useState<ModuleItem|null>(null),[mobileNav,setMobileNav]=useState(false);
 const metrics=industry==="塑膠製品業"?{risk:63,inventory:"1,248",high:37,sds:92,exp:[44,62,35,78,56,69],labels:["混料","射出","印刷","清洗","倉儲","維修"]}:{risk:71,inventory:"986",high:49,sds:87,exp:[58,74,49,82,67,72],labels:["配料","混煉","壓延","硫化","倉儲","維修"]};
 const filtered=useMemo(()=>groups.map(g=>({...g,items:g.items.filter(i=>(status==="全部"||i.status===status)&&(`${i.id}${i.name}${i.note}`).toLowerCase().includes(query.toLowerCase()))})).filter(g=>g.items.length),[query,status]);
 return <main className="app-shell">
  <aside className={`sidebar ${mobileNav?"open":""}`}><div className="brand"><div className="brand-mark"><span/><span/><span/></div><div><strong>CHEM<span>WISE</span></strong><small>化學品智慧管理平台</small></div></div><nav aria-label="主要導覽"><a className="active" href="#dashboard"><Icon name="dashboard"/>管理總覽</a><a href="#modules"><Icon name="modules"/>功能模組<span className="nav-count">25</span></a><a href="#dashboard"><Icon name="risk"/>風險與暴露</a><a href="#modules"><Icon name="inventory"/>庫存與流向</a><a href="#alerts"><Icon name="reports"/>稽核與報表</a></nav><div className="sidebar-bottom"><a href="#modules"><Icon name="settings"/>系統設定</a><div className="support"><span>需要協助？</span><strong>系統導入指南</strong><button>查看指南 →</button></div><div className="user"><div className="avatar">陳</div><div><strong>陳怡安</strong><small>職業安全衛生管理員</small></div><span>•••</span></div></div></aside>
  <section className="content"><header className="topbar"><button className="menu-btn" onClick={()=>setMobileNav(!mobileNav)} aria-label="開啟導覽">☰</button><div className="breadcrumb"><span>管理總覽</span><b>/</b><strong>全廠化學品風險</strong></div><div className="top-actions"><button className="icon-button" aria-label="通知">♢<i>3</i></button><button className="date-button">資料更新：2026/08/14 19:30</button></div></header>
   <div className="page-wrap"><section className="hero" id="dashboard"><div><div className="eyebrow"><span/>職場化學物質風險評估與管理實務架構</div><h1>事業單位化學品管理系統</h1><p>跨部門、全生命週期的化學品風險治理平台，將資料、法遵、暴露控制與永續績效整合為可行動的管理決策。</p></div><div className="hero-controls"><div className="segmented" role="group" aria-label="產業情境">{["塑膠製品業","橡膠製品業"].map(x=><button key={x} onClick={()=>setIndustry(x)} className={industry===x?"active":""}>{x}</button>)}</div><button className="primary-btn" onClick={()=>document.getElementById("modules")?.scrollIntoView({behavior:"smooth"})}>查看功能架構 <span>↓</span></button></div></section>
   <section className="summary-strip" aria-label="核心摘要"><div><span className="summary-icon blue">⌁</span><p>化學品主檔<strong>{metrics.inventory}</strong><small>較上月 +23</small></p></div><div><span className="summary-icon red">!</span><p>高風險物質<strong>{metrics.high}</strong><small>需優先管控</small></p></div><div><span className="summary-icon navy">✓</span><p>SDS 有效完整率<strong>{metrics.sds}%</strong><small>目標 ≥ 95%</small></p></div><div><span className="summary-icon steel">↗</span><p>本月改善結案<strong>18</strong><small>尚有 6 件追蹤中</small></p></div></section>
   <section className="dashboard-grid"><article className="panel gauge-panel"><div className="panel-head"><div><span>指針式</span><h2>整體化學風險指數</h2></div><em className="trend up">↑ 4.2%</em></div><Gauge value={metrics.risk}/><div className="risk-callout"><i/>目前為「中高風險」，優先檢視暴露評估逾期項目。</div></article><article className="panel heat-panel"><div className="panel-head"><div><span>熱力圖</span><h2>化學品風險矩陣</h2></div><button aria-label="更多選項">•••</button></div><Heatmap industry={industry}/><div className="legend"><span><i className="l1"/>低</span><span><i className="l2"/>中</span><span><i className="l3"/>高</span><span><i className="l4"/>極高</span></div></article><article className="panel bar-panel"><div className="panel-head"><div><span>直方圖</span><h2>製程暴露風險分布</h2></div><em>風險分數</em></div><div className="bar-chart">{metrics.exp.map((v,i)=><div className="bar-item" key={metrics.labels[i]}><b>{v}</b><div className="bar-track"><i style={{height:`${v}%`}} className={v>=75?"critical":v>=60?"warn":""}/></div><span>{metrics.labels[i]}</span></div>)}</div></article><article className="panel donut-panel"><div className="panel-head"><div><span>百分比</span><h2>年度風險改善完成率</h2></div><em className="trend">目標 90%</em></div><div className="donut-content"><Donut value={76}/><div className="donut-notes"><p><i className="done"/>已完成<strong>38</strong></p><p><i className="doing"/>執行中<strong>8</strong></p><p><i className="late"/>已逾期<strong>4</strong></p></div></div><div className="progress"><i style={{width:"76%"}}/></div></article></section>
   <section className="alerts" id="alerts"><div className="alert-title"><span>!</span><div><strong>今日有 6 項風險待處理</strong><small>3 份 SDS 即將失效 · 2 處儲存相容性異常 · 1 項暴露評估逾期</small></div></div><button onClick={()=>setStatus("注意")}>檢視待辦事項 →</button></section>
   <section className="module-section" id="modules"><div className="section-head"><div><span className="section-number">25</span><div><h2>模組化功能架構</h2><p>依化學品生命週期與企業治理需求彈性啟用，支援分階段建置。</p></div></div><div className="filter-tools"><label><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜尋功能或編號" aria-label="搜尋功能模組"/></label><select value={status} onChange={e=>setStatus(e.target.value)} aria-label="依狀態篩選"><option>全部</option><option>正常</option><option>注意</option><option>建置中</option></select></div></div><div className="module-groups">{filtered.map(group=><article className={`module-group ${group.color}`} key={group.key}><header><div className="group-symbol">{group.key==="foundation"?"◇":group.key==="lifecycle"?"↻":group.key==="risk"?"△":group.key==="compliance"?"§":"⌘"}</div><div><h3>{group.title}</h3><p>{group.subtitle}</p></div><span>{group.items.length} 項</span></header><div className="module-list">{group.items.map(item=><button key={item.id} onClick={()=>setSelected(item)}><span className="module-id">{item.id}</span><div><strong>{item.name}</strong><small>{item.note}</small></div><em className={`status ${item.status}`}>{item.status}</em><b>›</b></button>)}</div></article>)}{!filtered.length&&<div className="empty">找不到符合條件的功能模組，請調整搜尋關鍵字或狀態。</div>}</div></section>
   <footer><div className="footer-brand"><span>CHEM<span>WISE</span></span>｜事業單位化學品管理系統</div><p>示範資料僅供系統規劃與介面評估使用</p></footer></div></section>
  {selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)} role="presentation"><div className="modal" role="dialog" aria-modal="true" aria-labelledby="module-title" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)} aria-label="關閉">×</button><div className="modal-id">{selected.id}</div><h2 id="module-title">{selected.name}</h2><p>{selected.note}</p><div className="modal-grid"><div><span>建置狀態</span><strong>{selected.status}</strong></div><div><span>適用產業</span><strong>{industry}</strong></div><div><span>資料責任</span><strong>跨部門協作</strong></div><div><span>稽核軌跡</span><strong>完整保留</strong></div></div><button className="primary-btn" onClick={()=>setSelected(null)}>進入模組</button></div></div>}
 </main>
}
